package golang

const fileTpl = `
// Code generated by protoc-gen-enum-desc. DO NOT EDIT.
// source: {{ .InputPath }}

package {{ pkg . }}

import "google.golang.org/protobuf/reflect/protoreflect"

{{ range .AllEnums }}
	{{ template "enum" . }}
{{ end }}
`
