// Code generated by protoc-gen-enum-desc. DO NOT EDIT.
// source: foo.proto

package example

import "google.golang.org/protobuf/reflect/protoreflect"

var ServiceEvent_description = map[int32]string{
	0: "unspecified",
	1: "service start",
	2: "service stop",
}

func (x ServiceEvent) Description() string {
	return ServiceEvent_description[int32(protoreflect.EnumNumber(x))]
}

var Client_ClientEvent_description = map[int32]string{
	1: "client start",
}

func (x Client_ClientEvent) Description() string {
	if d := Client_ClientEvent_description[int32(protoreflect.EnumNumber(x))]; d != "" {
		return d
	}
	return "unknown client event"
}

func (x Client_Nest_ClientEvent) Description() string {
	return "unknown nest client event"
}
