// Code generated by protoc-gen-enum-desc. DO NOT EDIT.
// source: foo.proto

package example

var ServiceEvent_description = map[int32]string{
	// TODO
}

var Client_ClientEvent_description = map[int32]string{
	// TODO
}

var Client_Nest_ClientEvent_description = map[int32]string{
	// TODO
}
