// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        (unknown)
// source: foo.proto

package example

import (
	_ "github.com/windmeup/protoc-gen-enum-desc/proto/pged"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceEvent int32

const (
	ServiceEvent_SERVICE_EVENT_UNSPECIFIED ServiceEvent = 0
	ServiceEvent_SERVICE_EVENT_START       ServiceEvent = 1
	ServiceEvent_SERVICE_EVENT_STOP        ServiceEvent = 2
)

// Enum value maps for ServiceEvent.
var (
	ServiceEvent_name = map[int32]string{
		0: "SERVICE_EVENT_UNSPECIFIED",
		1: "SERVICE_EVENT_START",
		2: "SERVICE_EVENT_STOP",
	}
	ServiceEvent_value = map[string]int32{
		"SERVICE_EVENT_UNSPECIFIED": 0,
		"SERVICE_EVENT_START":       1,
		"SERVICE_EVENT_STOP":        2,
	}
)

func (x ServiceEvent) Enum() *ServiceEvent {
	p := new(ServiceEvent)
	*p = x
	return p
}

func (x ServiceEvent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceEvent) Descriptor() protoreflect.EnumDescriptor {
	return file_foo_proto_enumTypes[0].Descriptor()
}

func (ServiceEvent) Type() protoreflect.EnumType {
	return &file_foo_proto_enumTypes[0]
}

func (x ServiceEvent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceEvent.Descriptor instead.
func (ServiceEvent) EnumDescriptor() ([]byte, []int) {
	return file_foo_proto_rawDescGZIP(), []int{0}
}

type Client_ClientEvent int32

const (
	Client_CLIENT_EVENT_UNSPECIFIED Client_ClientEvent = 0
	Client_CLIENT_EVENT_START       Client_ClientEvent = 1
	Client_CLIENT_EVENT_STOP        Client_ClientEvent = 2
)

// Enum value maps for Client_ClientEvent.
var (
	Client_ClientEvent_name = map[int32]string{
		0: "CLIENT_EVENT_UNSPECIFIED",
		1: "CLIENT_EVENT_START",
		2: "CLIENT_EVENT_STOP",
	}
	Client_ClientEvent_value = map[string]int32{
		"CLIENT_EVENT_UNSPECIFIED": 0,
		"CLIENT_EVENT_START":       1,
		"CLIENT_EVENT_STOP":        2,
	}
)

func (x Client_ClientEvent) Enum() *Client_ClientEvent {
	p := new(Client_ClientEvent)
	*p = x
	return p
}

func (x Client_ClientEvent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Client_ClientEvent) Descriptor() protoreflect.EnumDescriptor {
	return file_foo_proto_enumTypes[1].Descriptor()
}

func (Client_ClientEvent) Type() protoreflect.EnumType {
	return &file_foo_proto_enumTypes[1]
}

func (x Client_ClientEvent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Client_ClientEvent.Descriptor instead.
func (Client_ClientEvent) EnumDescriptor() ([]byte, []int) {
	return file_foo_proto_rawDescGZIP(), []int{0, 0}
}

type Client_Nest_ClientEvent int32

const (
	Client_Nest_CLIENT_EVENT_UNSPECIFIED Client_Nest_ClientEvent = 0
	Client_Nest_CLIENT_EVENT_START       Client_Nest_ClientEvent = 1
	Client_Nest_CLIENT_EVENT_STOP        Client_Nest_ClientEvent = 2
)

// Enum value maps for Client_Nest_ClientEvent.
var (
	Client_Nest_ClientEvent_name = map[int32]string{
		0: "CLIENT_EVENT_UNSPECIFIED",
		1: "CLIENT_EVENT_START",
		2: "CLIENT_EVENT_STOP",
	}
	Client_Nest_ClientEvent_value = map[string]int32{
		"CLIENT_EVENT_UNSPECIFIED": 0,
		"CLIENT_EVENT_START":       1,
		"CLIENT_EVENT_STOP":        2,
	}
)

func (x Client_Nest_ClientEvent) Enum() *Client_Nest_ClientEvent {
	p := new(Client_Nest_ClientEvent)
	*p = x
	return p
}

func (x Client_Nest_ClientEvent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Client_Nest_ClientEvent) Descriptor() protoreflect.EnumDescriptor {
	return file_foo_proto_enumTypes[2].Descriptor()
}

func (Client_Nest_ClientEvent) Type() protoreflect.EnumType {
	return &file_foo_proto_enumTypes[2]
}

func (x Client_Nest_ClientEvent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Client_Nest_ClientEvent.Descriptor instead.
func (Client_Nest_ClientEvent) EnumDescriptor() ([]byte, []int) {
	return file_foo_proto_rawDescGZIP(), []int{0, 0, 0}
}

type Client struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Client) Reset() {
	*x = Client{}
	if protoimpl.UnsafeEnabled {
		mi := &file_foo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client) ProtoMessage() {}

func (x *Client) ProtoReflect() protoreflect.Message {
	mi := &file_foo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client.ProtoReflect.Descriptor instead.
func (*Client) Descriptor() ([]byte, []int) {
	return file_foo_proto_rawDescGZIP(), []int{0}
}

type Service struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Service) Reset() {
	*x = Service{}
	if protoimpl.UnsafeEnabled {
		mi := &file_foo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_foo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_foo_proto_rawDescGZIP(), []int{1}
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Client_Nest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Client_Nest) Reset() {
	*x = Client_Nest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_foo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Client_Nest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client_Nest) ProtoMessage() {}

func (x *Client_Nest) ProtoReflect() protoreflect.Message {
	mi := &file_foo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client_Nest.ProtoReflect.Descriptor instead.
func (*Client_Nest) Descriptor() ([]byte, []int) {
	return file_foo_proto_rawDescGZIP(), []int{0, 0}
}

var File_foo_proto protoreflect.FileDescriptor

var file_foo_proto_rawDesc = []byte{
	0x0a, 0x09, 0x66, 0x6f, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x70, 0x67, 0x65,
	0x64, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x1a, 0x13, 0x70, 0x67, 0x65, 0x64, 0x2f,
	0x65, 0x6e, 0x75, 0x6d, 0x64, 0x65, 0x73, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x95,
	0x02, 0x0a, 0x06, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x1a, 0x81, 0x01, 0x0a, 0x04, 0x4e, 0x65,
	0x73, 0x74, 0x22, 0x79, 0x0a, 0x0b, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x12, 0x1c, 0x0a, 0x18, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x5f, 0x45, 0x56, 0x45, 0x4e,
	0x54, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x16, 0x0a, 0x12, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f,
	0x53, 0x54, 0x41, 0x52, 0x54, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x43, 0x4c, 0x49, 0x45, 0x4e,
	0x54, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x53, 0x54, 0x4f, 0x50, 0x10, 0x02, 0x1a, 0x1d,
	0xd2, 0xa9, 0x04, 0x19, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x20, 0x6e, 0x65, 0x73, 0x74,
	0x20, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x20, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x86, 0x01,
	0x0a, 0x0b, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a,
	0x18, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x55, 0x4e,
	0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x28, 0x0a, 0x12, 0x43,
	0x4c, 0x49, 0x45, 0x4e, 0x54, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x52,
	0x54, 0x10, 0x01, 0x1a, 0x10, 0xd2, 0xa9, 0x04, 0x0c, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x20,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x15, 0x0a, 0x11, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x5f,
	0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x53, 0x54, 0x4f, 0x50, 0x10, 0x02, 0x1a, 0x18, 0xd2, 0xa9,
	0x04, 0x14, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x20, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x20, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x1d, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x2a, 0x94, 0x01, 0x0a, 0x0c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x2e, 0x0a, 0x19, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43,
	0x45, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x1a, 0x0f, 0xd2, 0xa9, 0x04, 0x0b, 0x75, 0x6e, 0x73, 0x70, 0x65,
	0x63, 0x69, 0x66, 0x69, 0x65, 0x64, 0x12, 0x2a, 0x0a, 0x13, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43,
	0x45, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x52, 0x54, 0x10, 0x01, 0x1a,
	0x11, 0xd2, 0xa9, 0x04, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x20, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x12, 0x28, 0x0a, 0x12, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x45, 0x56,
	0x45, 0x4e, 0x54, 0x5f, 0x53, 0x54, 0x4f, 0x50, 0x10, 0x02, 0x1a, 0x10, 0xd2, 0xa9, 0x04, 0x0c,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x20, 0x73, 0x74, 0x6f, 0x70, 0x42, 0x0b, 0x5a, 0x09,
	0x2e, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_foo_proto_rawDescOnce sync.Once
	file_foo_proto_rawDescData = file_foo_proto_rawDesc
)

func file_foo_proto_rawDescGZIP() []byte {
	file_foo_proto_rawDescOnce.Do(func() {
		file_foo_proto_rawDescData = protoimpl.X.CompressGZIP(file_foo_proto_rawDescData)
	})
	return file_foo_proto_rawDescData
}

var file_foo_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_foo_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_foo_proto_goTypes = []interface{}{
	(ServiceEvent)(0),            // 0: pged.example.ServiceEvent
	(Client_ClientEvent)(0),      // 1: pged.example.Client.ClientEvent
	(Client_Nest_ClientEvent)(0), // 2: pged.example.Client.Nest.ClientEvent
	(*Client)(nil),               // 3: pged.example.Client
	(*Service)(nil),              // 4: pged.example.Service
	(*Client_Nest)(nil),          // 5: pged.example.Client.Nest
}
var file_foo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_foo_proto_init() }
func file_foo_proto_init() {
	if File_foo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_foo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Client); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_foo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Service); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_foo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Client_Nest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_foo_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_foo_proto_goTypes,
		DependencyIndexes: file_foo_proto_depIdxs,
		EnumInfos:         file_foo_proto_enumTypes,
		MessageInfos:      file_foo_proto_msgTypes,
	}.Build()
	File_foo_proto = out.File
	file_foo_proto_rawDesc = nil
	file_foo_proto_goTypes = nil
	file_foo_proto_depIdxs = nil
}
